networks:
  frontend:
  backend:

secrets:
  db_password:
    file: db_password.txt

services:
#  productservice:
#    build: product_service
#    volumes:
#      - "./config:/config"
#      - "./product_service/src:/code"
#    secrets:
#      - db_password
#    networks:
#      - frontend
#      - backend
#    environment:
#      - DEBUG=False
#
#  web:
#    build: nginx
#    ports:
#      - "80:80"
#    networks:
#      - frontend
  db:
    image: mysql
    command: "--init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password"
    volumes:
      - "./db/init.sql:/data/application/init.sql"
      - "db-volume:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - backend
    ports:
      - "3306:3306"

volumes:
  db-volume:
